# Generated by Django 4.2.11 on 2024-03-26 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone number')),
                ('last_frontend_login', models.DateTimeField(blank=True, null=True, verbose_name='last frontend login')),
            ],
        ),
    ]
