# Generated by Django 4.2.13 on 2024-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('coffee', 'Coffee'), ('sugar', 'Sugar')], max_length=255, verbose_name='Type of inventory')),
                ('amount', models.FloatField(verbose_name='Amount')),
            ],
        ),
    ]
