# Generated by Django 4.2.11 on 2024-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Coffee Name')),
                ('price', models.IntegerField(verbose_name='Price of coffee')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image of coffee')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of coffee')),
                ('caffeine_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Caffeine Content')),
                ('origin', models.CharField(blank=True, null=True, verbose_name='Origin place of coffee')),
                ('roast_type', models.CharField(blank=True, choices=[('dark', 'Dark'), ('medium', 'Medium'), ('light', 'Light')], max_length=100, null=True, verbose_name='Roast type')),
                ('flavor_notes', models.TextField(blank=True, null=True, verbose_name='Flavor Notes')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
