# Generated by Django 4.2.13 on 2024-05-13 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=100, verbose_name='Coffee Size')),
                ('has_milk', models.BooleanField(default=False)),
                ('has_sugar', models.BooleanField(default=False)),
                ('milk_amount', models.IntegerField(blank=True, null=True, verbose_name='Milk Amount')),
                ('sugar_amount', models.IntegerField(blank=True, null=True, verbose_name='Sugar Amount')),
                ('water_amount', models.IntegerField(blank=True, null=True, verbose_name='Water Amount')),
                ('quantity', models.IntegerField(blank=True, default=1, verbose_name='Quantity')),
                ('coffee_amount', models.IntegerField(blank=True, null=True, verbose_name='Coffee Amount')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.coffee', verbose_name='Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name of table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='pending', max_length=100, verbose_name='Status')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('order', models.ManyToManyField(blank=True, to='order.order', verbose_name='Order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.table', verbose_name='Order of table')),
            ],
        ),
    ]
