# Generated by Django 4.2.13 on 2024-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_ordered_at_orderitem_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
